### ISSUE TITLE
Recurrent issue with sigma license

### ISSUE THREAD

**Issue by afcorral-desy** [sigma-py/quadpy#472]
When importing quadpy (updated version quadpy-0.16.27), I got the following error message:

"""
Warning: Unable to find valid license in

- environment variable PLM_LICENSE_KEY_SIGMA (env var not found), or
- config file /home/fernanda/.local/share/plm/sigma.toml (file not found)

Add a license with

    plm add <your-license-key>

"""

And then python kernel is killed. This error has happened recurrently but it has been previously solved after some time without needing of further updating.

Thanks for the help.

**Comment by nschloe** [comment]
Yeah, the release finally happened now. For more info, see [here](https://github.com/sigma-py). Let me know if you have any more questions!

**Comment by afcorral-desy** [comment]
Wow. This is very disappointing. 50 euros for a scientifically used software... That is not how science community should work if we want science to move forward.
I guess it is time to move on from quadpy/sigma.

**Comment by nschloe** [comment]
I tried to provide quadpy (and all other things) free of charge, but the donation-based model just didn't work. And after all, we all need to pay our rent, right? That's why I moved over to a commercial distribution model. If 50 Euros is too much for you or employer to afford, feel free to shoot a message to support@mondaytech.com, and we'll figure something out.

Anyway, much success on your scientific journey!

**Comment by nschloe** [comment]
@yachmena Thanks for the comment! quadpy had issued announcments about the upcoming change since Dec 1, 2022, so three months before the change happened. We think this is long enough to make a smooth transition for any developer. Sorry if it still caught you by surprise!

We'd love to keep you onboard as a user, and we'll try our best to enhance quadpy in ways that will be useful for anyone doing serious quadrature, both in terms of easy-of-use and computational speed. For example, all of our rules are well-tested, and there's a plethora to choose from for different applications. We think this easily justifies the moderate price tag.

Should you ever be unsatisfied with your own solutions, we'll be more than happy to welcome you back to Sigma/quadpy.

**Comment by shankarsivarajan** [comment]
> I guess it is time to move on from quadpy/sigma.

Or you can just use an older version.
